version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Okpe@123
      MYSQL_DATABASE: food_ordering
      MYSQL_USER: David
      MYSQL_PASSWORD: Okpe@123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  auth_service:
    image: davidokpe/auth_service
    environment:
      DB_NAME: food_ordering
      DB_USER: David
      DB_PASSWORD: Okpe@123
      DB_HOST: db
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
