version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Okpe@123
      MYSQL_DATABASE: food_ordering
      MYSQL_USER: David
      MYSQL_PASSWORD: Okpe@123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - my_custom_network
    ports:
      - "3306:3306"

  auth_service:
    image: davidokpe/auth_service
    container_name: auth_service_container
    environment:
      - DB_NAME=food_ordering
      - DB_USER=David
      - DB_PASSWORD=Okpe@123
      - DB_HOST=db
      - PORT=5000
    networks:
      - my_custom_network
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mysql_data:

networks:
  my_custom_network:
    driver: bridge
