version: '3.8'

services:
  auth_service:
    image: davidokpe/auth_service
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=food_ordering
      - DB_USER=root
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=db
      - PORT=5000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: food_ordering
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
