version: '3.8'

services:
  auth_service:
    image: davidokpe/auth_service
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=food_ordering
      - DB_USER=David
      - DB_PASSWORD=Okpe@123
      - DB_HOST=db  # Use the service name 'db' for inter-container communication
      - PORT=5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Okpe@123
      MYSQL_DATABASE: food_ordering
      MYSQL_USER: David
      MYSQL_PASSWORD: Okpe@123
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
